-- Exercise Backend Database Schema
-- Version: 1.1.0
-- Description: Schema with JWT authentication and role-based access control
-- Updated: 2024-12-19 - Added role column for RBAC support
-- Updated: 2024-12-19 - Removed _entity suffix from table names, added muscle_groups table

-- Drop existing tables if they exist (for fresh installations)
DROP TABLE IF EXISTS exercise_log_sets CASCADE;
DROP TABLE IF EXISTS exercise_sets CASCADE;
DROP TABLE IF EXISTS exercise_logs CASCADE;
DROP TABLE IF EXISTS exercises CASCADE;
DROP TABLE IF EXISTS muscle_groups CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Drop sequences if they exist
DROP SEQUENCE IF EXISTS users_seq;
DROP SEQUENCE IF EXISTS exercises_seq;
DROP SEQUENCE IF EXISTS exercise_logs_seq;
DROP SEQUENCE IF EXISTS muscle_groups_seq;

-- Create sequences for primary keys
CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE exercises_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE exercise_logs_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE muscle_groups_seq START WITH 1 INCREMENT BY 50;

-- Users table
CREATE TABLE users (
    id BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_role CHECK (role IN ('USER', 'ADMIN'))
);

-- Create indexes for users table
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);

-- Muscle groups table
CREATE TABLE muscle_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    CONSTRAINT uk_muscle_groups_name UNIQUE (name)
);

-- Create index for muscle group lookup
CREATE INDEX idx_muscle_groups_name ON muscle_groups(name);

-- Exercises table
CREATE TABLE exercises (
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    muscle_group_id BIGINT NOT NULL,
    CONSTRAINT fk_exercises_muscle_group FOREIGN KEY (muscle_group_id) REFERENCES muscle_groups(id)
);

-- Create index for exercise lookup
CREATE INDEX idx_exercises_name ON exercises(name);
CREATE INDEX idx_exercises_muscle_group ON exercises(muscle_group_id);

-- Exercise sets table (for workout sets)
CREATE TABLE exercise_sets (
    exercise_set_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight DOUBLE PRECISION,
    reps INTEGER
);

-- Exercise logs table (workout sessions)
CREATE TABLE exercise_logs (
    exercise_log_id BIGINT NOT NULL PRIMARY KEY,
    user_id BIGINT,
    exercise_id BIGINT,
    date TIMESTAMP(6),
    has_failed BOOLEAN NOT NULL,
    CONSTRAINT fk_exercise_logs_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_exercise_logs_exercise FOREIGN KEY (exercise_id) REFERENCES exercises(id)
);

-- Create indexes for exercise logs
CREATE INDEX idx_exercise_logs_user ON exercise_logs(user_id);
CREATE INDEX idx_exercise_logs_exercise ON exercise_logs(exercise_id);
CREATE INDEX idx_exercise_logs_date ON exercise_logs(date);

-- Exercise log sets (many-to-many relationship between logs and sets)
CREATE TABLE exercise_log_sets (
    exercise_log_id BIGINT NOT NULL,
    exercise_set_id BIGINT NOT NULL,
    PRIMARY KEY (exercise_log_id, exercise_set_id),
    CONSTRAINT fk_log_sets_log FOREIGN KEY (exercise_log_id) REFERENCES exercise_logs(exercise_log_id),
    CONSTRAINT fk_log_sets_set FOREIGN KEY (exercise_set_id) REFERENCES exercise_sets(exercise_set_id)
);

-- Create indexes for the join table
CREATE INDEX idx_log_sets_log ON exercise_log_sets(exercise_log_id);
CREATE INDEX idx_log_sets_set ON exercise_log_sets(exercise_set_id);

-- Comments for documentation
COMMENT ON TABLE users IS 'User accounts for the exercise tracking application';
COMMENT ON COLUMN users.role IS 'User role: USER (default) or ADMIN for administrative access';
COMMENT ON TABLE muscle_groups IS 'Muscle groups for exercise classification';
COMMENT ON TABLE exercises IS 'Available exercises with muscle group classification';
COMMENT ON TABLE exercise_logs IS 'Workout session logs for users';
COMMENT ON TABLE exercise_sets IS 'Individual sets within a workout';
COMMENT ON TABLE exercise_log_sets IS 'Relationship between workout logs and sets';

COMMENT ON COLUMN exercises.muscle_group_id IS 'Foreign key to muscle_groups table';
COMMENT ON COLUMN exercise_logs.has_failed IS 'Indicates if the set resulted in failure';
